services:
  app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: node --watch server.js

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
